<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">
  
    <PropertyGroup>
    <DefaultItemExcludes>$(DefaultItemExcludes);Tools\**</DefaultItemExcludes>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="8.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="8.0.0" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <GameImages Include="Assets\GameImages\**\*.*" />
    <SoundFiles Include="Assets\sounds\**\*.*" />
    <DataFiles Include="Assets\data\**\*.*" Exclude="Assets\data\day*.json;Assets\data\mielno_ending.json" />
  </ItemGroup>
  <Target Name="CleanGameImagesBeforeBuild" BeforeTargets="BeforeBuild;Publish">
    <ItemGroup>
      <OldImages Include="wwwroot\images\*" Exclude="wwwroot\images\av_*.jpg;wwwroot\images\bg_*.jpg;wwwroot\images\re_*.jpg" />
    </ItemGroup>
    <Delete Files="@(OldImages)" />
  </Target>
  <Target Name="CopyGameAssets" BeforeTargets="BeforeBuild">
    <Copy SourceFiles="@(GameImages)" 
          DestinationFolder="wwwroot\Images\%(RecursiveDir)" 
          SkipUnchangedFiles="true" />
    
    <Copy SourceFiles="@(SoundFiles)" 
          DestinationFolder="wwwroot\sounds\%(RecursiveDir)" 
          SkipUnchangedFiles="true" />
    
    <Copy SourceFiles="@(DataFiles)" 
          DestinationFolder="wwwroot\data\%(RecursiveDir)" 
          SkipUnchangedFiles="true" />
    
    <Message Importance="high" Text="Assets -> wwwroot: GameImages, sounds, data SKOPIOWANE" />
  </Target>

  <Target Name="BundleDaysToScenes" BeforeTargets="Build">
    <Exec Command="dotnet run --project Tools/BundleScenes.csproj -- $(MSBuildProjectDirectory)" />
  </Target>

</Project>